### ISSUE TITLE
Define data structures that would accommodate general purpose genetic workflows

### ISSUE THREAD

**Issue by eric-czech** [related-sciences/gwas-analysis#15]
It would be useful to document the capabilities of underlying data structures for existing genetic data file formats and processing platforms.  This issue should serve as a place to collect findings on what existing data structures look like and what dimensions they support, without an emphasis on how they are implemented.  At a minimum, this should cover:

- Hail 
- scikit-allele
- PLINK
- BGEN 

Some questions worth asking for these are:

- What ploidy does it support, if any beyond 2? 
- How does it accommodate probabilities instead of hard calls?
- Is phased data supported?
- Are variants x samples always the primary dimensions?  Do any formats/structures appeal to a more generic notions than these that are still more specific than rows/cols?
- Does it include time as a dimension, or anything else unusual beyond variants, samples, allele, and haplotype/genotype?
- Are genomic annotations included or used to enable some more useful analysis?
- What other WES/WGS considerations are made?
- How are copy number variants and gene dosage accounted for?
- Are other structural variants supported (beyond indels)?

**Comment by eric-czech** [comment]
### BGEN

- File Layout:
  - Offset from header block to data blocks
  - Header block 
    - Number of variants 
    - Number of samples 
    - Free data (e.g. custom identifying file info)
    - Flags 
      - Are there sample ids in the file (which follow header block)?
      - Is SNP data gzip compressed?
      - Which spec version is in use?
  - Sample ID block (optional)
  - Variant ID block 
    - rsid, chromosome, position
    - number of alleles (k) (16-bit)
    - individual alleles (k of them)
  - Genotype data block (Layout 2)
    - Layout 1 is deprecated and limited to diploid calls
    - Supports up to 2^16 alleles and ploidy up to 2^6 (phased or unphased)
    - All samples are compressed for a single variant when compression is enabled 
      - This implies format is not splittable in sample dimension, only variant dimension
    - Ploidy can differ for each sample (why would this ever be necessary?)
      - This is represented by N bytes (N = num samples) where 6 bits indicate ploidy and one bit indicates missingness 
    - All probabilities are represented as unsigned integers **X** where the probability is **X** / **max_int_value** with **max_int_value** being 2^B - 1 for some bit-depth B
    - **Phased**
      - Probabilities are stored consecutively in the order of haplotypes (i.e. chromosome) then alleles
      - Only k-1 probabilities are stored for k alleles (kth allele proba = 1 - sum of others)
    - **Unphased**
      - Because the order of the probabilities does not matter, the simultaneous probability of all genotypes is stored instead (the product of individual genotype probabilities)
      - Again though, one combination of genotypes can be omitted and computed later as a subtraction from 1
- Summary:
  - Data dimensions are variant, sample, chromosome and allele; limits:
    - variant + sample = 2^32
    - chromosome i.e. ploidy = 2^6 (64)
    - allele = 2^16 (65,535)
  - Phased calls and arbitrary ploidy are supported 
  - Only probabilities are supported, but you could just code hard calls as one genotype/haplotype w/ probability 1
  - BGEN is only splittable along the variant dimension (all samples expected to fit in memory for one variant)
  - Ploidy can actually change per-sample

**Comment by eric-czech** [comment]
### PLINK 

- Only bi-allelic, diploid organisms supported
- Does not support allele probabilities
  - These often result from sequencing data or imputed genotypes (viz. BEAGLE, MACH)
  - From https://www.cog-genomics.org/plink/1.9/formats#gen:
  > Since the PLINK 1 binary format cannot represent genotype probabilities, calls with uncertainty greater than 0.1 are currently treated as missing, and the rest are treated as hard calls. (This behavior can be changed with --hard-call-threshold.) We plan to remove this limitation in the future.
  - Probabilities are either used as sampling distributions for hard calls or inferred as missing if lowest probability is too high (for bi-allelic)
- Dosages are also not supported (i.e. allele counts)
- Copy number polymorphisms are supported but they are represented in separate gvar files 
  - This can be used as part of regression models that combine SNP and CNV data with special terms for SNPs within copy number segments (see [here](http://zzz.bwh.harvard.edu/plink/gvar.shtml) -- not sure what the state of this is in newer PLINK versions but it seems mostly incomplete)
- While haplotype phasing is possible with PLINK, it does not appear that ```.bed``` files actually carry this information (as Hail does)

**Comment by eric-czech** [comment]
### Scikit-Allele

- Supports polyploid organisms, multi-allelic sites, phased calls, CNVs
- Does not support genotype probabilities and no explicit mention of time and/or other structural variants is made in docs
- [GenotypeArray](https://scikit-allel.readthedocs.io/en/stable/model/ndarray.html#genotypearray)
  - Calls are represented as 3D integer arrays with shape (variant, sample, ploidy) and values correspond to allele index present
  - "0 is the reference allele, 1 is the first alternate allele, 2 is the second alternate allele, … and -1 (or any other negative integer) is a missing allele call"
  - Note that the number of alleles per-site does not need to be the same
  - An ```is_phased``` array with shape (variant, sample) maintains boolean flags for each call indicating whether or not it is phased
  - Phased calls are not represented differently from unphased ones, the tacit assumption is that when ```is_phased==True``` the order of the calls in the 3rd dimension has meaning
- [GenotypeAlleleCountsArray](https://scikit-allel.readthedocs.io/en/stable/model/ndarray.html#genotypeallelecountsarray) 
  - Alternative representation of GenotypeArray that allows for variable effective ploidy (i.e. **copy number variants**)
  - Phasing information is lost in this representation 
  - The shape is (variant, sample, allele) and each value corresponds to the number of occurrences of the corresponding allele
  - The number of alleles for each variant + sample can differ so the last dimension is as large as the maximum number of alleles across all variants
    - There is a ```max_allele``` function that returns the number of alleles as a 2D array w/ shape (variant, sample)
- [HaplotypeArray](https://scikit-allel.readthedocs.io/en/stable/model/ndarray.html#haplotypearray)
  - These are a single slice along the 3rd dimension of a GenotypeArray (with a reduced api)
  - This is what is required for functions that operate on phased data where individual haploids are required (viz. [Population Selection](https://scikit-allel.readthedocs.io/en/stable/stats/selection.html) methods)
- [VariantTable](https://scikit-allel.readthedocs.io/en/stable/model/ndarray.html#varianttable)
  - This is a table (np.recarray) that carries variant info like chromosome, position, read depths, quality scores, etc.
- [FeatureTable](https://scikit-allel.readthedocs.io/en/stable/model/ndarray.html#featuretable)
  - Genomic features table (very generic, provides little beyond using np.recarrays directly)

**Comment by eric-czech** [comment]
### Hail

- Supports polyploid organisms, multi-allelic sites, phased calls
- Genotype probabilities are supported, though only for diploid datasets when imported from bgen ([import_bgen](https://hail.is/docs/0.2/methods/impex.html?highlight=import_bgen#hail.methods.import_bgen))
  - Gene dosage can be calculated from this ([gp_dosage](https://hail.is/docs/0.2/functions/genetics.html?highlight=dosage#hail.expr.functions.gp_dosage))
  - Probabilities are stored as an array of genotype probabilities in the ```MatrixTable.GP``` property (this does not support phased probabilities)
- Does not support CNVs or large structural/nested variants
- [MatrixTable]()
  - Is conceptually a 2D call array w/ shape (variant, sample)
  - Variant and sample information is stored as 2D tables along both axes 
  - Calls can be attached as properties, typically ```GT```, and are represented as a  [CallExpression](https://hail.is/docs/0.2/hail.expr.CallExpression.html#hail.expr.CallExpression)
    - Stores allele index for each chromosome, making it identical in structure to scikit-allele GenotypeArray when embedded in MatrixTable
    - CallExpression also maintains ```phased``` flag and ```ploidy``` count
      - This makes is possible to mix calls w/ different phasing, ploidy, and allele count (it would make little sense to do so, but it is possible)
- Genomic annotations can be attached to variant info table along row axis 
  - e.g. [vep](https://hail.is/docs/0.2/methods/genetics.html?highlight=vep#hail.methods.vep) and [nirvana](https://hail.is/docs/0.2/methods/genetics.html#hail.methods.nirvana)

**Comment by hammer** [comment]
>variable effective ploidy (i.e. copy number variants)

I'm a bit confused as to how copy number variants and ploidy are related. I would imagine coding the copy number as a distinct allele. For example, if at a certain locus across the population there are alleles with 1, 2, or 3 copies, then support for multiple alleles seems sufficient to capture this information. If these genomes are phased, then you can put a copy number on each copy of the chromosome, but the ploidy should not change, unless my understanding of the molecular biology of CNVs is off?

Also, on the support for multiple alleles: are there any explicit carve-outs for the MHC locus? If we want to use this software for infectious disease susceptibility analyses, for example, that locus becomes critical, and is obviously highly polymorphic so likely stresses whatever support is available for multiple alleles at a locus.

**Comment by eric-czech** [comment]
Good point.  "Effective ploidy" is a term I first say in the scikit-allele docs and does seem to be used elsewhere as being synonymous with copy number variation ([1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4775221/) [2](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.2004644)).  I agree that thinking of a variant on a single chromosome as having some kind of variable ploidy is weird. 

If I'm understanding the scikit-allele GenotypeAlleleCountsArray model correctly though, I believe it is implying that, for example, a diploid organism could have two different alleles that are each copied some different number of times.  In your example, are you saying that for 2 alleles and each of 1, 2 or 3 copies there would be 6 possible alleles (i.e. each allele + copy number combination)?

My guess would be that PLINK and scikit-allele use separate data structures for CNVs entirely since the analysis they run on them requires the count numbers in some matrix form anyhow, so they simply never need to find a way to represent them in a multi-allelic encoding like you mentioned.  

Separately, this is probably worth a read at some point if it's not already on the paper queue: [Whole-genome sequencing reveals high complexity of copy number variation at insecticide resistance loci in malaria mosquitoes](https://genome.cshlp.org/content/early/2019/07/19/gr.245795.118.full.pdf)

**Comment by eric-czech** [comment]
I am imagining that the best starting point for a data structure is an Nd array with shape (variants, samples, allele, ploidy) and with values equal to either dosages, probabilities, or copy number (entirely equal to 1 in most cases) -- whatever is appropriate for the analysis.  Let me know if my understanding of copy number representation in the last comment doesn't match with yours.

I'm also planning to start on a prototype that defines this and some appropriate degenerate cases, e.g. haplotypes for diploid, bi-allelic hard calls, as Xarray subclasses.  My plan is for the prototype to work like this, when it comes to data structures:

```python
# Load genotype data, possible from PLINK/bgen
arr = xr.DataArray(...) 
# Build subclass object (this is where all preconditions will be applied)
gt = api.GeneticDataArray(arr) 

# Do something within the API, which will not operate on raw Xarray classes
gt = api.ld_prune(gt) 

# Do something outside the API
def my_custom_analysis(gt: xarray.Dataset) -> xarray.Dataset:
   ... # Do some stuff that only operates on xarray structures
   return gt
gt = my_custom_analysis(gt)

# Convert back to API structures if necessary by invoking the appropriate constructor
gt = api.GeneticDataArray(gt) 
```

Any thoughts/concerns?

**Comment by eric-czech** [comment]
I've got what I think is a pretty solid start on this up now at https://github.com/related-sciences/gwas-analysis/blob/master/notebooks/platform/xarray/examples.ipynb.

The internals for it are in https://github.com/related-sciences/gwas-analysis/tree/master/notebooks/platform/xarray/lib.

**Comment by eric-czech** [comment]
I refactored this nearly from scratch into [data_stuctures.ipynb](https://nbviewer.jupyter.org/github/related-sciences/gwas-analysis/blob/90ad3822b03e72e59f71453992ff12a94deee60a/notebooks/platform/xarray/data_structures.ipynb) ([internals](https://github.com/related-sciences/gwas-analysis/tree/90ad3822b03e72e59f71453992ff12a94deee60a/notebooks/platform/xarray/lib)).  This version is much better, with some notable differences being:

- All data structures are now ```Dataset``` subclasses rather than ```DataArray```
- This includes models for phasing and missing data (Xarray does not support masking)
- Dispatching was added to masked array backends (this is apparently not within the purview of \_\_array\_function\_\_ protocol implementations)

**Comment by GianDevi** [comment]
I am working on the genome .my background is from computer science. plz, guide which dataset or type of dataset busing any tool like crisper or whatever..... plz guide..thanks in advance.

**Comment by eric-czech** [comment]
Closing and adding any more updates related to xarray prototyping in https://github.com/related-sciences/gwas-analysis/issues/5
