### ISSUE TITLE
Determine core operations necessary in general-purpose GWAS toolkits

### ISSUE THREAD

**Issue by eric-czech** [related-sciences/gwas-analysis#16]
As a complement to https://github.com/related-sciences/gwas-analysis/issues/15, this [spreadsheet](https://docs.google.com/spreadsheets/d/1FPen1xGMuzc-s0y0cSHuz1RFaiGdmS1ZL8mvUROSm1E/edit?usp=sharing) shows the functionality present in several toolkits as well as properties of the data structures that back them.

This also shows which libraries do or do not have "core" features, according to what I've seen to be most common in the workflows I've been studying.  Particularly notable capabilities and deficiencies are also pointed out which should make it easier to build a narrative about the landscape.

This issue should be closed out once we're convinced nothing important is missing.

**Comment by eric-czech** [comment]
Note to self: add GENESIS

**Comment by hammer** [comment]
I wonder if a comparison to the most popular pipeline of single-purpose tools is worth including as well? Something like https://github.com/kerimoff/qcnorm, for example.

Also [GCTA](https://cnsgenomics.com/software/gcta) might be considered a toolkit by this point given its growth in scope.

**Comment by eric-czech** [comment]
cf. https://discourse.smadstatgen.org/t/core-operations-in-human-gwas-workloads/41

Looking at qcnorm briefly:
- [pop_assign.nf](https://github.com/kerimoff/qcnorm/blob/master/pop_assign.nf) appears to be most relevant
- Use of [ldak](http://dougspeed.com/ldak/) isn't something I've seen before
- Aside from `ldak`, the order and intent of all the plink operations is familiar (`ldak` is used for kinship / PCA calcs so presumably it's not that different anyhow)

For qcnorm and TOPMed, the general order of operations in the pipelines squares with everything else I've seen -- it's basically the same stuff accomplished in completely different ways.  I think we're unlikely to be surprised by anything on this front now until we get into processing WES data or normalizing phenotypes ourselves.
