### ISSUE TITLE
Zarr/packgeneticbits invalid missing values encoding

### ISSUE THREAD

**Issue by ravwojdyla** [related-sciences/gwas-analysis#33]
See an issue description [here](https://render.githubusercontent.com/view/ipynb?commit=052507786d350a1a5950975fae55c1953c9070e6&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f72656c617465642d736369656e6365732f677761732d616e616c797369732f303532353037373836643335306131613539353039373566616535356331393533633930373065362f6e6f7465626f6f6b732f706c6174666f726d2f7861727261792f70635f72656c6174652f70635f72656c6174652e6970796e62&nwo=related-sciences%2Fgwas-analysis&path=notebooks%2Fplatform%2Fxarray%2Fpc_relate%2Fpc_relate.ipynb&repository_id=232396500&repository_type=Repository#WIP:-Zarr-issue) under "WIP: Zarr issue".

**Comment by eric-czech** [comment]
Note: need to add some IO unit tests as well
