### ISSUE TITLE
PyData PC-Relate Integration

### ISSUE THREAD

**Issue by eric-czech** [related-sciences/gwas-analysis#35]
We need to incorporate @ravwojdyla's PC-Relate work.  

I'm going to wait on that though until we get @tomwhite's take on dispatching and the overall organization.

Note: The biggest remainder from Rafal's work is that PCs for PC-Relate are supposed to be generated using unrelated individuals.  GENESIS does this with a first-order approximation to kinship using KING (which doesn't account for admixture like PC-Relate does) followed by PCA on unrelated people, and then finally projection for all people to create PCs for PC-Relate.  Hail ignores these parts, or doesn't provide anything for them, so we'll have to decide what our first-order kinship equivalent is, and if it needs to be robust to population structure.  GRM/IBD within self-reported ancestral groups may be enough given that we'll always have that info in human GWAS based on high profile datasets.

**Comment by tomwhite** [comment]
I think @ravwojdyla's work could be merged here. Work on dispatch is going to continue in the sgkit repo now.
